name: Deployment with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jaydev5546/node:${{ github.sha }}
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 16.171.153.101
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            echo "Starting deployment"
            sudo docker stop node-app
            sudo docker run -d --name node-app -p 5000:5000 jaydev5546/node:${{ github.sha }}